// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  call_to_action: dynamic(() => import("./CallToAction")),
  experience_header: dynamic(() => import("./ExperienceHeader")),
  home_header: dynamic(() => import("./HomeHeader")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  projects: dynamic(() => import("./Projects")),
  text_and_description: dynamic(() => import("./TextAndDescription")),
  text_block: dynamic(() => import("./TextBlock")),
};
