// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  navigation_item: dynamic(() => import("./NavigationItem")),
  paragraph: dynamic(() => import("./Paragraph")),
};
